---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      python:
        patterns: ['*']
  - package-ecosystem: docker
    directories: [/backend, /frontend]
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      docker:
        patterns: ['*']
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      infrastructure:
        patterns: ['*']
