#!/usr/bin/env bash
set -euo pipefail

displayUsage() {
    echo '
usage:  correct-new-submissions [...]
operations:
    {-h help}    shows this dialogue
    {-n number}  number of times to run the correction
    {-d daemon}  keep running until process is closed
    {-t time}    time to wait before next iteration in minutes
    {-f failed}  correct failed assignment
    {-v verbose} verbosity
    {-a all}     correct all assignments'
}

# check requirements
bash check_requirements || exit 1

# check for network
if [ ! wget -q --spider http://google.com ]
then
    echo "No connection to the internet"
    exit 1
fi

n=1
t=0
daemon=false
args=''
download_args=''
while getopts ":hn:dt:va" opt; do
    case ${opt} in
	a)
	    grade_all=true
	    args+='a'
	    ;;
	d)
	    daemon=true
	    ;;
	f)
	    download_args='f'
	    ;;
	h)
	    displayUsage
	    exit 0
	    ;;
	n)
	    n="$OPTARG"
	    ;;
	t)
	    t=$OPTARG
	    ;;
	v)
	    verbose=true
	    args+='v'
	    download_args+='v'
	    ;;
	\?)
	    echo "Invalid option: $OPTARG" 1>&2
	    exit 2
	    ;;
	:)
	    echo "Invalid option: $OPTARG requires an argument" 1>&2
	    exit 2
	    ;;
    esac
done

shift $((OPTIND - 1))

[ ! -z "$args"] && args+='-$args'
[ ! -z "$download_args"] && args+='-$download_args'

function routine {
    echo "
    ################################################################################
    #                           deleting old submissions                           #
    ################################################################################"
    bash delete_submissions.sh
    echo "Done deleting old submissions!"

    echo "
    ################################################################################
    #                           Downloading submissions                            #
    ################################################################################
    "
    if [ ! -z "$download_args" ]; then
	python3 download_submissions.py "$download_args"
    else
	python3 download_submissions.py
    fi
    echo "Done downloading submissions"

    echo "
    ################################################################################
    #                             process submissions                              #
    ################################################################################"
    bash process_submissions.sh
    echo "Done correcting submissions!"

    echo "
    ################################################################################
    #                              uploading comments                              #
    ################################################################################"
    python upload_comments.py -v
    echo "Done uploading comments!"

    echo "
    ################################################################################
    #                               updating grades                                #
    ################################################################################"
    python grade_submissions.py -v
    echo "Done updating grades!"

    echo "
    ################################################################################
    #                               plotting results                               #
    ################################################################################"
    python plot_scores.py
    date
    echo "Done plotting"
}

while true; do

    time routine

    if [ "$n" -gt "0" ]; then
	n=$((n - 1))
    fi
    if [ "$n" -gt "0" ] || $daemon; then
	echo "
	################################################################################
	#                                   waiting                                    #
	################################################################################"
	! $daemon && date && echo "Runs left: $n" || date && echo "Running as daemon"
	while :; do for s in / - \\ \|; do
			printf "\r$s"
			sleep 0.2
		    done; done &
	sleep "$t"m
	kill $!
	trap 'kill $!' SIGTERM
    fi
    if [ "$n" = "0" ] && [ "$daemon" = "false" ]; then
	break
    fi
done

echo "Autorun: Done!"
