#+TITLE: Automated Correction Framework for Applied Programming at Univeristy of Copenhagen
#+AUTHOR: Jakob G. Aaes
#+EMAIL: (concat "jakob1379" at-sign "gmail.com")

* Ideas/ToDo [8/14]
  :PROPERTIES:
  :COOKIE_DATA: recursive
  :END:

  This chapter notes ideas for future implementation.
  * [ ] find a better name than correct-submissions
  * [ ] change upload_comment and grade_submission to take the assignment object by extracting the assignment object outside of the function. There is no need to pass all assignment to the function.
  * [ ] change plotting according to Kenny' suggestions
  * [ ] add the sns.clustermap
  * [ ] rewrite bcolors to be functions that appends and prepends rather than being plain strings
  * [ ] Common example usecases e.g. how to correct a single student/assignment etc.
  * [ ] Move assignments to a single folder called *assignments* for easier iteration through each assignment
  * [X] Setup script:
    This script should go through all the necessary steps to start running the code checking
    1. [X] enter token
    2. [X] check validity of token
    3. [X] enter course id
    4. [X] setup assignments folders according to the assignments on absalon
    5. [X] Enter points required for completing each assignment
    6. [X] Upload scores or not i.e. is the assignments scored or simply passed/failed
    7. [X] What files to uploads i.e. give filenames or regex
