#!/usr/bin/env bash

top_dir="$PWD"
for submission in Week*/submissions/*/; do
    cd "$top_dir/$submission"
    bname=$(basename "$submission")
    zip_name=$(basename "$submission" | sed 's/ /+/g')
    zip "$zip_name.zip" "$bname.txt" "errors.log"
done
