#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

lines=$(grep -P "^\w+.*=" config.ini)
section=""

declare -A config

# echo "found variables and values"
# for line in $lines; do

#     value=$(echo "$line" | awk -F '=' '{print $2}')
#     config[$index]="$value"
#     # echo "$index: $value"
# done

while read -r line; do
    if [[ "$line" =~ ^\[.*\]$ ]]
    then
	section=$(echo "$line" | tr --delete '\[\]')
    elif [[ "$line" =~ ^# ]]
    then
	continue
	echo "COMMENT: $line"
    else
	index=$(echo "$line" | awk -F '=' '{print $1}')
	value=$(echo "$line" | awk -F '=' '{print $2}')
	config[$section/$index]="$value"
    fi
done < config.ini

export config
