#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'


top_dir="$PWD"
for submission in $(find -mindepth 3 -maxdepth 3  -type d -wholename "*submissions*"); do
    cd "$top_dir/$submission"
    bname=$(basename "$submission")
    zip_name=$(basename "$submission" | sed 's/ /+/g')

    if [ -f "$bname.txt" ] || [ ! -z "$(find -type f -name '*.log')" ]; then
       zip -X -q "$zip_name.zip" "$bname.txt" *.log
    fi
done
